### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Dieterbe** [geckoboard/prism#14]
Hello,
prism looks really neat. am looking forward to play with it.

I have read https://medium.com/geckoboard-under-the-hood/introducing-prism-9c08e9926755 and also the README, but still have 2 questions:

1) while both the blog post and readme explain well how the call graph stuff works, it's still unclear how the profiling on a per-goroutine basis works: invoking prism seems to be with a method or function as target, and the output seems to be per-target-function also. so what if this target is invoked in multiple goroutines? does it measure the overhead of each part of the stack on a per-goroutine basis? how is that reflected in the output?  I'm guessing the hooks that are inserted ensure accounting on a per-goroutine-id basis, but this wasn't really clear from the articles, nor the example output.

2) let's say we target function A, and A calls function B. what happens if B is also called by other functions that have nothing to do with A? will invocations of B caused by C (not A) also be measured? what happens to the results of the measurements? are they mixed with the results of the invocations made by A ?

thanks!

**Comment by achilleasa** [comment]
Hello. Thanks for your interest in prism.

Your assumption that the hooks work on a per-goroutine-id basis is correct. Prism injects two types of hooks:
- a `Begin/EndProfile` call is injected into the target functions. 
- a `Enter/Exit` call is injected into functions that may be potentially invoked by a target function.

The `BeginProfile` call initializes a blank profile linked to the go-routine ID that was active when the hook was invoked. Calls to `Enter/Exit` figure out the current go-routine ID and lookup the profile based on that ID so that additional data can be appended. If no valid profile can be found, then the hooks will behave as a no-op.

Here is a small example that shows how this works in the scenarios you describe in both questions:

```go
package main

import (
	"fmt"
	"sync"
	"time"
)

func work() {
	fmt.Println("work called")
}

func A() {
	work()
}

func B() {
	work()
}

func main() {
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < 100; i++ {
			B()
			<-time.After(100 * time.Millisecond)
		}
	}()

	for i := 0; i < 100; i++ {
		A()
		<-time.After(100 * time.Millisecond)
	}
	wg.Wait()
}
```

For the first scenario, we specify `A` as our function target. Prism will hook `A` (with `Begin/EndProfile`) and `work` (with `Enter/Exit`). When `A` gets called, it initiates a new profile for the main go-routine (say with ID `1`); when `work` gets called by `A` it will lookup the profile for go-routine `1` and append its data. When `work()` gets called by `B` inside the spawned go-routine (say with ID `2`), the call to `Enter` will not be able to lookup the profile with ID `2` and will just bail out.

Let's try a different scenario were we specify both `A` and `B` as prism targets. In this case as you correctly point out `work` will get invoked by different go-routines. Prism will isolate the calls to `work` per go-routine and it will emit two distinct captured profiles whose file names are built-using the following pattern: `profile-$target_name-$ns_timestamp-$go_routine_id.json`.

**Comment by Dieterbe** [comment]
sweet. and so my second item is not an issue, because if C calls B then it'll only be accounted for if it's in the same goroutine as A, and if we're within a call to A. If A terminates and then B calls C it'll be after EndProfile and no-opped.

that's really slick, thank you :)
